# Generated by Django 4.1.5 on 2023-03-09 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('phone', models.CharField(max_length=15, verbose_name='Phone')),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_agent', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=255, verbose_name='Bank Name')),
                ('account_number', models.CharField(max_length=255, verbose_name='Account Number')),
                ('account_name', models.CharField(max_length=255, verbose_name='Account Name')),
            ],
            options={
                'verbose_name_plural': 'Bank Details',
            },
        ),
        migrations.CreateModel(
            name='HouseAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office', models.CharField(max_length=255, verbose_name='Address')),
                ('NIN', models.CharField(blank=True, max_length=255, null=True, verbose_name='NIN')),
                ('valid_id', models.ImageField(blank=True, null=True, upload_to='house_agent', verbose_name='Valid ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='house_agent', verbose_name='Image')),
                ('bank_details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='house_agent', to='users.bankdetails')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='house_agent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'House Agents',
            },
        ),
    ]
