# Generated by Django 4.1.5 on 2023-02-18 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accommodationspace',
            options={'verbose_name_plural': 'Accommodation Spaces'},
        ),
        migrations.AddField(
            model_name='accommodationspace',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='accommodationspace',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
    ]
