# Generated by Django 4.1.5 on 2023-03-09 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accommodation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='_rating',
            field=models.ManyToManyField(related_name='accommodation_rating', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accommodation.category'),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='images',
            field=models.ManyToManyField(related_name='accommodation_images', to='accommodation.images'),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accommodation.location'),
        ),
    ]
