# Generated by Django 4.1.5 on 2023-03-10 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accommodation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterModelOptions(
            name='images',
            options={},
        ),
    ]
