# Generated by Django 4.1.5 on 2023-02-18 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0002_alter_accommodationspace_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccommodationType',
            new_name='AccommodationCategory',
        ),
        migrations.AlterModelOptions(
            name='accommodationcategory',
            options={'verbose_name_plural': 'Accommodation Categories'},
        ),
        migrations.AlterModelOptions(
            name='accommodationimages',
            options={'verbose_name_plural': 'Accommodation Images'},
        ),
        migrations.RenameField(
            model_name='accommodationspace',
            old_name='rating',
            new_name='_rating',
        ),
        migrations.RenameField(
            model_name='accommodationspace',
            old_name='type',
            new_name='category',
        ),
    ]
