# Generated by Django 4.1.5 on 2023-02-18 09:40

import accommodation.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0004_alter_accommodationspace_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodationspace',
            name='id',
            field=models.CharField(default=accommodation.models.customId, editable=False, max_length=20, primary_key=True, serialize=False),
        ),
    ]
