# Generated by Django 4.1.5 on 2023-02-18 09:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accommodation', '0005_alter_accommodationspace_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accommodationspace',
            name='_rating',
        ),
        migrations.AddField(
            model_name='accommodationspace',
            name='_rating',
            field=models.ManyToManyField(related_name='accommodation_rating', to=settings.AUTH_USER_MODEL),
        ),
    ]
