# Generated by Django 4.1.5 on 2023-02-18 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0006_remove_accommodationspace__rating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accommodationcategory',
            old_name='type',
            new_name='category',
        ),
    ]
