# Generated by Django 4.1.5 on 2023-02-18 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0008_alter_accommodationspace_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodationimages',
            name='first_thumbnail',
            field=models.ImageField(blank=True, upload_to='accommodation_images'),
        ),
    ]
