# Generated by Django 4.1.5 on 2023-02-18 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0010_rename_first_thumbnail_accommodationimages__first_thumbnail_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accommodationspace',
            old_name='image',
            new_name='images',
        ),
        migrations.AddField(
            model_name='accommodationspace',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='accommodation_images'),
        ),
    ]
