# Generated by Django 4.1.5 on 2023-02-18 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0011_rename_image_accommodationspace_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodationspace',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='accommodationspace',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
