# Generated by Django 4.1.5 on 2023-02-18 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0012_accommodationspace_name_accommodationspace_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodationspace',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
