# Generated by Django 4.1.5 on 2023-02-18 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0013_accommodationspace_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodationspace',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accommodation.location'),
        ),
    ]
