# Generated by Django 4.1.5 on 2023-02-19 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0014_accommodationspace_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodationspace',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
