# Generated by Django 4.1.5 on 2023-02-19 10:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0016_alter_accommodationspace_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodationspace',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='accommodationspace',
            name='update_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
