# Generated by Django 4.1.5 on 2023-02-19 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0018_alter_accommodationspace_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accommodationspace',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
