# Generated by Django 4.1.5 on 2023-02-19 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0019_rename_update_at_accommodationspace_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accommodationimages',
            name='_first_thumbnail',
        ),
        migrations.RemoveField(
            model_name='accommodationimages',
            name='_second_thumbnail',
        ),
        migrations.RemoveField(
            model_name='accommodationimages',
            name='_third_thumbnail',
        ),
        migrations.RemoveField(
            model_name='accommodationimages',
            name='first',
        ),
        migrations.RemoveField(
            model_name='accommodationimages',
            name='second',
        ),
        migrations.RemoveField(
            model_name='accommodationimages',
            name='third',
        ),
        migrations.AddField(
            model_name='accommodationimages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='accommodation_images'),
        ),
        migrations.RemoveField(
            model_name='accommodationspace',
            name='images',
        ),
        migrations.AddField(
            model_name='accommodationspace',
            name='images',
            field=models.ManyToManyField(related_name='accommodation_images', to='accommodation.accommodationimages'),
        ),
    ]
