# Generated by Django 4.1.5 on 2023-02-19 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0021_accommodationimages_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodationspace',
            name='description',
            field=models.TextField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accommodationspace',
            name='name',
            field=models.CharField(blank=True, default='hello', max_length=255),
            preserve_default=False,
        ),
    ]
