# Generated by Django 4.1.5 on 2023-02-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0022_alter_accommodationspace_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodationspace',
            name='description',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='accommodationspace',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
